# Generated by Django 4.2.6 on 2023-10-06 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['date', 'title'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
    ]
